### ISSUE TITLE
Outdated and Incorrect Information

### ISSUE THREAD

**Issue by polymo1** [asdfzxcvbn/instructions#1]
Hello, I am a member of the @SideStore team.

Recently, we had a user ask for support, and linked your instructions.

Your instructions reference AltStore and Sideloadly as installation options, and says that public anisette servers lock accounts.

As I know, the former was never the correct or functional way to install sidestore, and the latter is no longer true.

Please remove, update, or include a link to our docs in this repo.

For any questions, please ask here, or email me at wes@sidesto.re

Thanks!

**Comment by asdfzxcvbn** [comment]
hi, this repo is over a year old, i'll go ahead and link to your new instructions and archive this repo. thanks!
